services:
  stereo-obstaculos:
    build: .
    container_name: stereo-obstaculos
    restart: unless-stopped

    # 🔑 Darle acceso completo a los dispositivos (para descartar restricciones)
    privileged: true

    devices:
      # Exponemos ambos devices tal cual están en el host
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"

    group_add:
      - "video"

    ports:
      - "8080:8080"

    environment:
      # El cambio a '0' se realiza porque la prueba confirmó que es el índice de video correcto.
      LEFT_DEV: "0"
      RIGHT_DEV: "" # modo SBS (una sola cámara)
      WIDTH: "1344"
      HEIGHT: "376"
      FPS: "15"

    volumes:
      - ./data:/app/data
